### ISSUE TITLE
Latest pull of bite requires command line parameter

### ISSUE THREAD

**Issue by smaudet** [WINSDK/bite#14]
I'm using rust-rover to build your project, nice initial UI! It was perfect for seeing some things fast, obviously not quite feature complete.

I went from 7c4ef57 to 0f15d2e to see if I could get any new features, and well, this new version has one major flaw.

Before I would start it, go file->open and it would work fine (couldn't close the file). Now, it needs a command line parameter. I can of course, modify my run configuration, however that's clumsy at best. I tried commenting out your error message, and that half-worked (it appears you try to load immediately on startup).

If there's not a file parameter, the program shouldn't exit, it should just start up, maybe warn there's no file (and maybe add a parameter so I can squash that warning from my run config).

**Comment by WINSDK** [comment]
Yeah sorry, didn't realize I made launching bite require a path. 
The PR looks simple enough, I'll merge it rq.
