### ISSUE TITLE
Default color MAGENTA is completely unreadable on grey background.

### ISSUE THREAD

**Issue by AndreasOM** [WINSDK/bite#9]
I know you can change it in the config,
but it would be nice if I could read the text on a vanilla startup.

Quick hack I did locally -- in tokenizing/src/lib.rs
```
    //pub const MAGENTA: Color = color!(0xf5, 0x12, 0x81);
    pub const MAGENTA: Color = color!(0xf5, 0x62, 0x81);
```

**Comment by WINSDK** [comment]
I'll get the colorscheme system to include all colored things in the GUI.
When that's done it shouldn't be too hard to try making the text more readable.

**Comment by WINSDK** [comment]
Commits 2614c7a675ea0a78a9e2158265649851843b7c8f and 4e7dab4abd09e18dadc15d6386302bc947065c9b add more more options to the colorscheme for this kinda thing now.
Changed the color in 67bf3ae45d0b3ae8463f56bd8b3c241d34ab2c36.

**Comment by AndreasOM** [comment]
Much better!

Thank you!
